[package]
name = "os-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"   # cli argument parser
walkdir = "2.5.0" # recursively search Cargo.toml for finding packages
self_cell = "1.0.4" # self-referential 

serde = { version = "1", features = ["derive"] }
marked-yaml = { version = "0.7.1", features = ["serde-path"] } # parse yaml file
cargo_metadata = "0.18.1" # parse metadata for knowing project layout
serde_json = "1.0.120"
prettydiff = { version = "0.7.0", default-features = false }
regex = "1.10.5"
compact_str = "0.8.0"
itertools = "0.13.0"
ahash = "0.8.11"
tabled = { version = "0.15.0", features = ["ansi"] }
owo-colors = { version = "4.0.0", features = ["supports-colors"] }

# error handling
eyre = "0.6.12"
color-eyre = "0.6.3"

# logger
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# shell commands
duct = "0.13.7" # better subprocess, pipe, redirct
yash-syntax = "0.10.0" # shell lang parsing

[dev-dependencies]
expect-test = "1.5.0" # use `UPDATE_EXPECT=1 cargo t` to update all tests
