[package]
name = "os-checker-types"
version = "0.3.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
compact_str = { workspace = true }
camino = { workspace = true }

